# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160322_1110'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='pos',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
