# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20160325_1008'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracked_Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracked_word', models.CharField(max_length=100)),
            ],
        ),
    ]
