# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-24 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_word_pos'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcomment',
            name='words',
            field=models.ManyToManyField(to='news.Word'),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='words',
            field=models.ManyToManyField(to='news.Word'),
        ),
    ]
