# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-26 02:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_auto_20160324_0934'),
        ('news', '0005_tracked_word'),
    ]

    operations = [
    ]
