# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 09:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tracked_word',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 27, 9, 34, 59, 531775)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tracked_word',
            name='facebook_comment',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.FacebookComment'),
        ),
        migrations.AddField(
            model_name='tracked_word',
            name='facebook_post',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.FacebookPost'),
        ),
        migrations.AddField(
            model_name='tracked_word',
            name='news_article',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Article'),
        ),
        migrations.AlterField(
            model_name='tracked_word',
            name='tracked_word',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
