# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 10:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0008_auto_20160327_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tracked_word',
            name='facebook_comment',
        ),
        migrations.AddField(
            model_name='tracked_word',
            name='facebook_comment',
            field=models.ManyToManyField(blank=True, default='', null=True, to='news.FacebookComment'),
        ),
        migrations.RemoveField(
            model_name='tracked_word',
            name='facebook_post',
        ),
        migrations.AddField(
            model_name='tracked_word',
            name='facebook_post',
            field=models.ManyToManyField(blank=True, default='', null=True, to='news.FacebookPost'),
        ),
        migrations.RemoveField(
            model_name='tracked_word',
            name='news_article',
        ),
        migrations.AddField(
            model_name='tracked_word',
            name='news_article',
            field=models.ManyToManyField(blank=True, default='', null=True, to='news.Article'),
        ),
    ]
