# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 11:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0010_auto_20160327_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='tracked_word',
            new_name='tracked_words',
        ),
    ]
