# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-27 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0011_auto_20160327_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='facebookcomment',
            name='tracked_words',
            field=models.ManyToManyField(to='news.Tracked_Word'),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='tracked_words',
            field=models.ManyToManyField(to='news.Tracked_Word'),
        ),
    ]
