# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-31 13:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0012_auto_20160327_1236'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['-tracked', 'word']},
        ),
        migrations.RemoveField(
            model_name='article',
            name='tracked_words',
        ),
        migrations.RemoveField(
            model_name='facebookcomment',
            name='tracked_words',
        ),
        migrations.RemoveField(
            model_name='facebookpost',
            name='tracked_words',
        ),
        migrations.AddField(
            model_name='word',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='word',
            name='tracked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='word',
            name='pos',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='word',
            unique_together=set([('word', 'pos')]),
        ),
        migrations.DeleteModel(
            name='Tracked_Word',
        ),
    ]
