# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 08:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0014_auto_20160402_2002'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iword', models.CharField(max_length=200)),
                ('tracked', models.BooleanField(default=False)),
            ],
        ),
        migrations.AlterModelOptions(
            name='word',
            options={'ordering': ['word']},
        ),
        migrations.RemoveField(
            model_name='word',
            name='tracked',
        ),
        migrations.AddField(
            model_name='tag',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Word'),
        ),
    ]
