# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 09:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0015_auto_20160403_0843'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='word',
        ),
        migrations.AddField(
            model_name='word',
            name='tag',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='news.Tag'),
        ),
    ]
