# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0017_auto_20160403_1329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='iword',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
