# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0019_auto_20160403_1408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.Tag'),
        ),
    ]
