# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-03 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0020_auto_20160403_1455'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['-tracked', 'iword']},
        ),
    ]
