# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-22 04:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0022_wordsfilter'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='WordsFilter',
            new_name='FilteredWord',
        ),
    ]
