# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-25 19:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0023_auto_20160422_0458'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FilteredWord',
        ),
        migrations.AddField(
            model_name='tag',
            name='filtered',
            field=models.BooleanField(default=False),
        ),
    ]
