# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-29 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0025_auto_20160428_1930'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='words',
            field=models.ManyToManyField(to='news.Word'),
        ),
    ]
