# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-30 19:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0028_facebookapisetting_twitterapisetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='nltkized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebookcomment',
            name='nltkized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='facebookpost',
            name='nltkized',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tweet',
            name='nltkized',
            field=models.BooleanField(default=False),
        ),
    ]
