# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 13:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0031_auto_20160503_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tweet',
            name='stream',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.TwitterStream'),
        ),
    ]
