# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-03 14:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0035_auto_20160503_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='twitterstream',
            name='started',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
